import {StyleSheet} from 'react-native';
import { Colors } from './DartboardZones';

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#b2b8fd',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    height: '100%',
    width: '100%',
  },
  throwsArea: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    position: 'absolute',
    width: 280,
    bottom: 60,
    fontSize: 18,
    fontWeight: '600',
    margin: 5,
    padding: 15,
    borderRadius: 15,
  },
  svgStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    margin: 0,
  },
  scoreArea: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    position: 'absolute',
    width: 280,
    maxHeight: 160,
    top: 50,
    fontSize: 18,
    fontWeight: '600',
    margin: 5,
    overflow: 'scroll',
    padding: 15,
    borderRadius: 15,
  },
  finalScoreArea: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    width: 280,
    maxHeight: 460,
    fontSize: 18,
    fontWeight: '600',
    margin: 5,
    overflow: 'scroll',
    padding: 15,
    borderRadius: 15,
  },
  scoreText: {
    color: Colors.blue,
    fontSize: 18,
    textTransform: 'uppercase',
    paddingHorizontal: 20,
  },
  button: {
    margin: '1%',
    padding: '5',
    backgroundColor: '#dc244b',
    padding: 10,
    borderRadius: 10,
    textAlign: 'center',
    color: 'white',
  },
  Dartbutton: {
    margin: '1%',
    padding: '5',
    backgroundColor: '#dc244b',
    padding: 10,
    borderRadius: 10,
    textAlign: 'center',
    color: 'white',
    position: 'absolute',
    bottom: 1,
  },
  buttonText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
  },
  playerName: {
    textAlign: 'center',
    color: Colors.blue,
    fontSize: 16,
  },
  heading: {
    fontSize: 24,
    fontWeight: 'bold',
    marginVertical: 20,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  input: {
    borderWidth: 2,
    borderColor: Colors.white,
    padding: 8,
    flex: 1,
    marginRight: 10,
    borderRadius: 10,
  },
  playerItem: {
    color: Colors.blue,
    flexDirection: 'row',
    backgroundColor: Colors.white,
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    padding: 10,
    borderRadius: 10,
    marginBottom: 5
  },
  list: {
    width: '90%',
    height: '90%',
    alignItems: 'center'
  },
  row: {
    paddingTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  boldScoreText: {
    color: Colors.red,
    fontSize: 18,
    textTransform: 'uppercase',
    paddingHorizontal: 20,
    fontWeight: 'bold',
  },
});

export default styles;
